#!/bin/zsh
# extract the x,y,z values from the xtc file
# where z > 0

fn=/Users/george/track_plans/nmra-wimrr-2-flat.xtc
ofn=data/elevations.csv
echo "x,y,z">$ofn
echo "Input: $fn"
grep  T4 $fn| awk  'BEGIN {IFS = " "}; {OFS=","};\
    {if (($9 + 0) > 0) {print $3, $4, $9}}' | sort | uniq \
    >> $ofn
echo "Output: $ofn"